name: Deploy to Azure Static Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: github-repo-manager/package-lock.json

      - name: Install Dependencies
        working-directory: github-repo-manager
        run: |
          npm ci

      - name: Debug Versions
        working-directory: github-repo-manager
        run: |
          node --version
          npm --version
          npx vite --version

      - name: Build with Vite
        working-directory: github-repo-manager
        run: |
          npx tsc -b
          npx vite build --mode production
        env:
          VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
          VITE_GITHUB_REDIRECT_URI: ${{ secrets.VITE_GITHUB_REDIRECT_URI }}
          VITE_GITHUB_CLIENT_SECRET: ${{ secrets.VITE_GITHUB_CLIENT_SECRET }}
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: List Build Output
        run: ls -la github-repo-manager/dist/

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string


      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "github-repo-manager"
          output_location: "github-repo-manager/dist"
          skip_app_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}
