name: Deploy to Azure Static Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clear npm cache and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
        working-directory: github-repo-manager

      - name: Debug Node.js and Vite versions
        run: |
          node --version
          npm --version
          npx vite --version
        working-directory: github-repo-manager

      - name: Run build environment check
        run: node debug-build.js
        working-directory: github-repo-manager

      - name: TypeScript compilation
        run: npx tsc -b
        working-directory: github-repo-manager

      - name: Build application with Vite
        run: npx vite build --mode production
        env:
          VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
          VITE_GITHUB_REDIRECT_URI: ${{ secrets.VITE_GITHUB_REDIRECT_URI }}
          VITE_GITHUB_CLIENT_SECRET: ${{ secrets.VITE_GITHUB_CLIENT_SECRET }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        working-directory: github-repo-manager

      - name: Copy dist to build (Oryx workaround)
        run: |
          mkdir -p github-repo-manager/build
          cp -r github-repo-manager/dist/* github-repo-manager/build/

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "github-repo-manager"
          output_location: "github-repo-manager/build"
          skip_app_build: true
